apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app-deployment
  namespace: app1
spec:
  selector:
    matchLabels:
      app: sample-app-nodejs
  replicas: 2
  template:
    metadata:
      labels:
        app: sample-app-nodejs
    spec:
      containers:
      - name: sample-app-nodejs
        image: index.docker.io/starkandwayne/sample-app-nodejs:0.0.1
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: sample-app-nodejs
spec:
  selector:
    app: sample-app-nodejs
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
