apiVersion: v1
kind: Pod
metadata:
  labels:
    type: app
  name: net-tools
  namespace: default
spec:
  containers:
  - name: busybox
    image: nicolaka/netshoot
    args:
    - sleep
    - "1000"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    type: app
  name: node-app
  namespace: default
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    type: app
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: node-app1
  namespace: app1
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    type: app
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: node-app2
  namespace: app2
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    type: app
  type: ClusterIP
---
apiVersion: v1
kind: Pod
metadata:
  name: node-app
  namespace: default
  labels:
    type: app
spec:
  containers:
    - name: node-app
      image: index.docker.io/starkandwayne/sample-app-nodejs:0.0.1
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    type: app
  name: net-tools
  namespace: app1
spec:
  containers:
  - name: busybox
    image: nicolaka/netshoot
    args:
    - sleep
    - "1000"
---
apiVersion: v1
kind: Pod
metadata:
  name: net-tools
  namespace: app2
  labels:
    type: app
spec:
  containers:
  - name: busybox
    image: nicolaka/netshoot
    args:
    - sleep
    - "1000"
---
apiVersion: v1
kind: Pod
metadata:
  name: node-app
  namespace: app1
  labels:
    type: app

spec:
  # hostname: node-app1
  # subdomain: default-subdomain
  containers:
    - name: node-app
      image: index.docker.io/starkandwayne/sample-app-nodejs:0.0.1
---
apiVersion: v1
kind: Pod
metadata:
  name: node-app
  namespace: app2
  labels:
    type: app
spec:
  # hostname: node-app2
  # subdomain: default-subdomain
  containers:
    - name: node-app
      image: index.docker.io/starkandwayne/sample-app-nodejs:0.0.1