apiVersion: v1
kind: Pod
metadata:
  name: quota-pod
  namespace: app1
  labels:
    type: app
spec:
  containers:
    - name: node-app
      image: index.docker.io/starkandwayne/sample-app-nodejs:0.0.1
      # resources:
      #   requests:
      #     # memory: "1024Mi"  # too big
      #     memory: "512Mi"
      #     cpu: "250m"
      #   limits:
      #     memory: "1024Mi"
      #     cpu: "500m"
